//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ovresko.Generix.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class CultureSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CultureSettings defaultInstance = ((CultureSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CultureSettings())));
        
        public static CultureSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultCultureName {
            get {
                return ((string)(this["DefaultCultureName"]));
            }
            set {
                this["DefaultCultureName"] = value;
            }
        }
    }
}
